'use strict';
/* Reference pre-review for the calibration deck (Quartus AI Fund II LP, 28 pages, institutional).
   Written to the reviewer's verdicts on the finding sheet. Used when Claude is unavailable in a view,
   and as the "what good looks like" comparison after a live run. Shaped exactly like model output. */
const Fixture = (() => {
  const profile = {
    material_kind: 'fund pitch deck',
    subject: 'Quartus AI Fund II LP, a venture growth equity fund investing in AI-based software companies (target $150M, hard cap $250M)',
    lane: 'institutional',
    lane_basis: 'Questionnaire: institutional investors only. Page 27 states a $100K minimum for individual investors, which is a fund term, not a statement about this material\'s audience.',
    deal_related: true,
    page_roles: { 1: 'cover', 2: 'toc', 3: 'disclaimers', 4: 'risk factors', 5: 'section divider', 6: 'executive summary', 7: 'team', 8: 'team (advisors)', 9: 'performance', 10: 'section divider', 11: 'mission', 12: 'values', 13: 'strategy', 14: 'section divider', 15: 'market', 16: 'strategy (illustration)', 17: 'strategy (focus areas)', 18: 'portfolio (allocation)', 19: 'section divider', 20: 'process', 21: 'process', 22: 'process', 23: 'service providers', 24: 'section divider', 25: 'portfolio (target companies)', 26: 'section divider', 27: 'terms', 28: 'contact' },
    coverage: {
      forward_looking: { covered: true, where: 'Page 3, paragraph 5; footnotes on pages 9 and 25 cross-reference the Disclaimers on page 3', quote: 'Projected future performance data, particularly on pages 9 and 25, is treated as forward looking.' },
      past_performance: { covered: true, where: 'Page 3, paragraph 3', quote: 'Past performance is not indicative of future results. There can be no assurance that any of the funds or Opportunities will achieve the targeted returns.' },
      risk_of_loss: { covered: true, where: 'Page 3 and the Key Risk Factors on page 4', quote: 'All investments involve risk. You may lose part or all of your investment.' },
      targets_not_guaranteed: { covered: true, where: 'Page 4, Performance Goals and Underwriting Standards', quote: 'there can be no assurance that any targeted return for an investment or, in the aggregate, for the Fund, will be achieved' },
      illiquidity: { covered: true, where: 'Page 4, Lack of Liquidity', quote: 'Interests in the Fund are not redeemable.' },
      third_party_sources: { covered: true, where: 'Page 15 (Goldman Sachs reports), page 9 footnotes (audited statements), page 25 footnote 1', quote: "Sources: Goldman Sachs' Powering the AI Era report and Navigating the AI Era report" },
      preferred_return: { covered: false, where: '', quote: '' },
      logos: { covered: false, where: '', quote: '' },
      awards: { covered: false, where: 'The cover award carries no disclosure; the page 6 benchmark claim is footnoted (Cambridge Associates)', quote: '' },
      finalis_bd: { covered: false, where: '', quote: '' },
    },
    sources_on_pages: { 9: 'Footnotes 1-3: audited financial statements 2016-2021; projection basis; cross-reference to the Disclaimers on page 3', 15: "Sources: Goldman Sachs' Powering the AI Era and Navigating the AI Era reports; Quartus research", 16: 'FOR ILLUSTRATIVE PURPOSES ONLY; footnote 1 on the baseline exit scenario (no data source)', 18: 'FOR ILLUSTRATIVE PURPOSES ONLY; actual results may vary', 20: 'Footnote 1: baseline exit scenario criteria', 25: 'Footnote 1: Company provided and/or Quartus projected based on its analysis; footnote 3 cross-references the Disclaimers on page 3' },
    audience_signals: ['Page 27: "Minimum Commitment $1M for institutional and $100K for individual investors"'],
    third_party_prepared: false,
    notes: ['The deck carries a full disclaimers page (3) and a key risk factors page (4); triggered disclosures for projections and past performance are covered there.', 'The Finalis disclaimer and the institutional legend are absent (deterministic).'],
  };

  const batch = {
    findings: [
      { rule: 'B4', severity: 'high', page: 27, pages: [27], quote: 'Preferred Return 8%', title: 'Preferred return shown without the preferred-return disclosure', issue: 'The fund terms state an 8% preferred return and no page explains that it is a distribution sequence, not a guaranteed or projected return.', text_to_add: RULES.SOP.pref, rewrite: '', action: 'add', placement: 'Disclaimers page 3 (or a footnote on page 27)', confidence: 'high', basis: 'SOP (c) Preferred Returns; reviewer verdict: correct flag, add to the disclaimers page' },
      { rule: 'B8', severity: 'medium', page: 1, pages: [1], quote: 'US Emerging Manager Best Performance Award 2024', title: 'Award on the cover without the award disclosure', issue: 'The cover shows a Private Equity Wire award and DDX/FactRight verification badges without naming the awarding organization\'s role, the criteria, the period covered or whether any fee was paid.', text_to_add: 'Disclose the name of the organization that issued the award, its role in the selection, the criteria applied, the period covered, and whether any fee was paid to be considered or to use the award.', rewrite: '', action: 'add', placement: 'Footnote on page 1 or the Disclaimers page 3', confidence: 'high', basis: 'SOP 5(a) awards; reviewer verdict: well flagged' },
      { rule: 'B6', severity: 'medium', page: 23, pages: [23], quote: 'Funds’ Technology Stack & Service Providers', title: 'Service provider logos without the logo disclosure', issue: 'Page 23 displays the logos of auditors, administrators, custodians and vendors as relationships of the firm; the SOP requires the logo disclosure on the page where they appear.', text_to_add: RULES.SOP.logos, rewrite: '', action: 'add', placement: 'Page 23, below the logo panels', confidence: 'high', basis: 'SOP (7) Corporate Logos; reviewer verdict: correct flag' },
      { rule: 'A7', severity: 'medium', page: 16, pages: [16], quote: 'FOR ILLUSTRATIVE PURPOSES ONLY', title: 'Illustrative chart without a source line', issue: 'The multiplier-effect chart plots value, risk and liquidity by stage with no source; the legend says it is illustrative but does not say where the data comes from.', text_to_add: RULES.SOP.source, rewrite: '', action: 'source', placement: 'Page 16, next to the illustrative legend', confidence: 'medium', basis: 'SOP (b) market data and statistics; reviewer verdict: correct flag' },
      { rule: 'C4', severity: 'medium', page: 6, pages: [6], quote: 'benefit from the trillions of dollars being poured into foundational AI infrastructure', title: 'Market figure stated as fact with no source on the page', issue: 'A specific industry capital figure is asserted on page 6 with no source; page 15 cites Goldman Sachs for a similar statement, page 6 does not.', text_to_add: '', rewrite: 'benefit from the significant capital being invested in foundational AI infrastructure (Source: Goldman Sachs, Powering the AI Era)', action: 'source', placement: '', confidence: 'high', basis: 'Framework: sources for factual claims; calibration rule 10(b); reviewer verdict: correct flag' },
      { rule: 'C4', severity: 'medium', page: 1, pages: [1], quote: 'Led by AI pioneers, technologists and seasoned operators', title: '"AI pioneers" is an unsupported characterization', issue: 'The cover characterizes the team as pioneers as a matter of fact, with nothing in the material supporting the term.', text_to_add: '', rewrite: 'Led by experienced AI technologists and seasoned operators', action: 'rewrite', placement: '', confidence: 'high', basis: 'Language Guide 2(a); framework: industry-leading management team example; reviewer verdict: correct flag' },
      { rule: 'C4', severity: 'low', page: 17, pages: [17], quote: 'Opportunities that offer attractive long-term growth potential in the US, Europe and Asia.', title: 'Growth potential stated as fact rather than belief', issue: 'The sentence asserts that the focus areas offer attractive growth potential; framing it as the firm\'s view keeps it fair and balanced.', text_to_add: '', rewrite: 'Opportunities that we believe offer attractive long-term growth potential in the US, Europe and Asia.', action: 'rewrite', placement: '', confidence: 'medium', basis: 'Language Guide, lack of substantiation: state opinions as opinions; reviewer verdict: correct flag' },
      { rule: 'C1', severity: 'medium', page: 21, pages: [21], quote: 'Investor of choice for many companies', title: '"Investor of choice" is a self-endorsement without support', issue: 'A claim about how companies perceive the firm, stated as fact and unsupported in the material.', text_to_add: '', rewrite: 'Selected as investor by a number of portfolio companies', action: 'rewrite', placement: '', confidence: 'medium', basis: 'Language Guide, lack of substantiation; no reviewer verdict on this item (open)' },
      { rule: 'C6', severity: 'medium', page: 22, pages: [22], quote: 'Investing at a lower valuation than our VC/PE peers allows for a return of capital', title: 'Comparison to peers stated as fact', issue: 'The statement compares the firm\'s entry valuations to its peers without a basis; on institutional material the comparison must still be supportable.', text_to_add: '', rewrite: 'Seeking to invest at lower valuations than typical VC/PE rounds is intended to support a return of capital', action: 'escalate', placement: '', confidence: 'medium', basis: 'Framework: comparisons case by case; calibration rule 10(d); no reviewer verdict on this item (open)' },
      { rule: 'C2', severity: 'low', page: 21, pages: [21, 22], quote: 'Actively Monitor & Fortify Portfolio To Achieve 4x Plus Target Fund Returns', title: 'Headline reads as an outcome although it names a target', issue: 'The headline on pages 21 and 22 pairs "to achieve" with "target"; a reviewer may read it as a stated outcome. Close call under the framework, so escalate rather than assert.', text_to_add: '', rewrite: 'Actively Monitor & Fortify Portfolio, Targeting 4x Plus Fund Returns', action: 'escalate', placement: '', confidence: 'low', basis: 'Framework: "on track to deliver" example; calibration rule 13 (close calls); no reviewer verdict on this item (open)' },
      { rule: 'C1', severity: 'low', page: 22, pages: [22], quote: 'proven business models', title: '"proven" used as an absolute', issue: 'The language guide lists "proven" among absolute words to qualify; on institutional material this is a light point.', text_to_add: '', rewrite: 'established business models', action: 'rewrite', placement: '', confidence: 'low', basis: 'Language Guide 2(a); no reviewer verdict on this item (open)' },
      { rule: 'B10', severity: 'low', page: 27, pages: [27], quote: '$100K for individual investors', title: 'Fund terms mention individual investors; confirm the audience', issue: 'The questionnaire says institutional only while the terms table quotes a minimum for individual investors. This is a fund term, not necessarily this material\'s audience; a one-line confirmation from the banker settles it.', text_to_add: '', rewrite: '', action: 'confirm', placement: '', confidence: 'low', basis: 'Calibration rule 8: explicit audience statements only, low severity' },
    ],
    suppressed: [
      { rule: 'B1', pages: [9, 25, 27], quote: '7.65x Projected TVPI / Projected MOIC / Target Return 4x TVPI, 20% IRR', reason: 'Page 3 states that projected data is forward-looking and may not be realized; footnotes on pages 9 and 25 cross-reference it. Calibration rule 3.' },
      { rule: 'B2', pages: [9, 16, 18, 25], quote: 'projection chart / FOR ILLUSTRATIVE PURPOSES ONLY', reason: 'Illustration disclosure covered by the disclaimers page and the illustrative legends on pages 16 and 18.' },
      { rule: 'B3', pages: [9], quote: 'Past Fund (2016-2021), 2.10x TVPI, 8.90% Net IRR', reason: '"Past performance is not indicative of future results" on page 3, with the audited-statement basis footnoted on page 9. Not bold and standalone, which the SOP prefers; not worth a request on institutional material.' },
      { rule: 'B3', pages: [4, 6, 7], quote: 'Fund II / Fund I has been in the top quartile / Relevant Track Record', reason: 'Risk factors, a footnoted benchmark statement and team bios are not performance data.' },
      { rule: 'B6', pages: [7, 8, 12, 17, 25], quote: 'Prior Work / Education logos, advisor photos, values icons, target portfolio investors and clients', reason: 'Bios, values icons and target-portfolio company relationships are not third-party endorsements of the issuer. Calibration rule 6.' },
      { rule: 'B8', pages: [6], quote: 'Fund I has been in the top quartile for most of the past 2+ years', reason: 'Footnote 1 names the Cambridge Associates benchmark and vintage. Calibration rule 7.' },
      { rule: 'B9', pages: [3, 12], quote: 'real estate project / property', reason: 'The past fund invested in a real estate project; this offering is a venture fund.' },
      { rule: 'B10', pages: [3], quote: 'You may lose part or all of your investment', reason: 'Risk language never signals the audience. Calibration rule 8.' },
      { rule: 'A7', pages: [9, 25], quote: 'Fund Performance & Projections / Target Investment Portfolio', reason: 'Both pages carry source footnotes (audited statements; company provided and/or Quartus projected).' },
      { rule: 'A7', pages: [7, 27], quote: 'team bios / fund terms', reason: 'Not statistical exhibits.' },
      { rule: 'C1', pages: [6, 15], quote: 'We believe Vertical AI offers the best risk-adjusted return potential', reason: 'Stated as the firm\'s belief; page 15 also cites its sources. Calibration rule 9(a).' },
      { rule: 'C1', pages: [6], quote: 'some of the largest global institutions', reason: 'Descriptive of third parties the team worked with. Calibration rule 9(g).' },
      { rule: 'C2', pages: [6, 13, 18], quote: 'to deliver strong risk-adjusted returns / accelerate growth / designed to deliver', reason: 'Aspirational statements of what the firm aims to do, with the illustrative legend on page 18. Calibration rule 9(a).' },
      { rule: 'C4', pages: [7], quote: '$1B+ AUM, 20+ ventures with 10+ successful exits, 300+ ventures reviewed', reason: 'Biographical experience of the team. Calibration rule 9(c).' },
      { rule: 'C4', pages: [9, 16, 20], quote: '7.65x Projected TVPI / Base Case 10x Exit Potential / 10x Plus Exit Potential', reason: 'Labelled projected, key target metric or potential with footnoted basis. Calibration rule 9(e).' },
      { rule: 'C6', pages: [9], quote: 'Past Fund (2016-2021) next to Quartus AI Fund LP', reason: 'Labelled past fund with its strategy difference disclosed on page 3. Calibration rule 9(f).' },
      { rule: 'C1', pages: [11, 20], quote: 'delivers superior risk-adjusted returns / exceptional technology companies', reason: 'Mission statement of what the firm aims for; page 20 footnotes the selection criteria; institutional lane is lighter.' },
      { rule: 'C9', pages: [6, 7, 13, 17, 21], quote: 'benefit-only pages', reason: 'The deck has a Key Risk Factors page; no per-page risk language is requested on institutional material. Calibration rule 4.' },
      { rule: 'C13', pages: [4, 6, 8, 9, 12, 15, 22, 25, 27], quote: 'bold body text', reason: 'Formatting is not a standard item on institutional material.' },
    ],
    gut_check: {
      inaccurate_picture: { flag: false, why: 'Disclaimers and key risk factors are prominent (pages 3 and 4) and projection slides cross-reference them.' },
      unsupported_claims: { flag: true, why: '"AI pioneers" (p.1), the unsourced market figure (p.6), "investor of choice" (p.21) and the peer valuation comparison (p.22) could not be backed up from the material.' },
      promised_results: { flag: false, why: 'Returns are framed as targets, projections and potential; the page 21/22 headline is the only close call.' },
    },
    brief: 'Quartus AI Fund II LP pitch deck, 28 pages, institutional investors only, deal-related. The deck carries a full Disclaimers page (3) and a Key Risk Factors page (4); projections and past performance on pages 9 and 25 cross-reference them, so no forecast, illustration or past-performance disclosure is requested.\nRequired blocks: the Finalis disclaimer with the broker-dealer line is missing, and the "For Institutional Investors Only" legend is absent from the cover. Both are firm policy for this lane.\nTriggered disclosures: the 8% preferred return (p.27) needs the SOP preferred-return text, best placed on page 3; the cover award (p.1) needs the award disclosure; the service-provider logos (p.23) need the logo line; the illustrative chart on page 16 has no source.\nLanguage: "AI pioneers" (p.1), the unsourced "trillions of dollars" figure (p.6) and "opportunities that offer attractive long-term growth potential" (p.17) are the points to send. "Investor of choice" (p.21), the peer valuation comparison (p.22) and the "To Achieve 4x Plus" headline are close calls to escalate rather than assert.\nSet aside: 19 candidates a naive scan would have raised (projection slides covered by page 3, bios, values icons, footnoted benchmark, "we believe" statements, formatting).',
    banker_message: 'Hello [Banker Name], hope you\'re doing well. Could you please make the following changes to the Quartus AI Fund II deck before we can approve it:\n\n1. Add the Finalis disclaimer, for example on the Disclaimers page (page 3) or the last page: "' + RULES.SOP.finalis_full + '"\n\n2. Add "For Institutional Investors Only" in a visible part of the first page.\n\n3. Preferred return (page 27): please add the following on page 3 or as a footnote on page 27: "' + RULES.SOP.pref + '"\n\n4. Award on the cover: please disclose the awarding organization and its role in the selection, the criteria used, the period covered, and whether any fee was paid for participation, consideration or receipt of the award.\n\n5. Page 23 (service providers): please add "Corporate logos do not represent endorsements."\n\n6. Page 16: please add a source for the chart, or "Source: Information provided by Sponsoring/Issuing Company."\n\n7. Wording: page 1 "AI pioneers" (please confirm the basis or replace with "experienced AI technologists"); page 6 "trillions of dollars being poured into foundational AI infrastructure" (please add the source, as on page 15, or soften to "significant capital"); page 17 "Opportunities that offer attractive long-term growth potential" (please frame as "that we believe offer"); page 21 "Investor of choice for many companies" (please support or soften); page 22 "lower valuation than our VC/PE peers" (please provide the basis for the comparison or soften).\n\nThank you.',
  };

  function build(facts, form, pages) {
    const out = Review.assemble(facts, form, profile, [batch], pages, { reference: true });
    out.meta = { calls: [], reference: true, note: 'Reference pre-review written to the reviewer\'s verdicts on this deck (finding sheet, Finalis AI hackathon).' };
    out.pages = pages;
    out.facts = facts;
    return out;
  }
  return { build, profile, batch };
})();
